#!/bin/bash
# Export dynamic job: run janus-cli export-dynamic for the ibutsu plugin and pack the output.
# Allow lockfile updates during export-dynamic (janus-cli runs yarn install internally)
export YARN_ENABLE_IMMUTABLE_INSTALLS=false

yarn workspace @redhatinsights/backstage-plugin-ibutsu export-dynamic

cd plugins/ibutsu/ || exit 1
rm -f *.tgz
npm pack ./dist-dynamic
cd ../..

mv plugins/ibutsu/*.tgz .

# Output checksum for the dynamic plugin tarball (version from plugins/ibutsu/package.json)
IBUTSU_VERSION=$(node -p "require('./plugins/ibutsu/package.json').version")
TARBALL="redhatinsights-backstage-plugin-ibutsu-dynamic-${IBUTSU_VERSION}.tgz"
if [ -f "$TARBALL" ]; then
  fsha=$(sha256sum "$TARBALL" | awk '{print $1}' | xxd -r -p | base64)
  echo "Ibutsu: sha256-${fsha}"
fi
