#!/bin/bash

yarn workspace @redhatinsights/backstage-plugin-ibutsu export-dynamic
cd plugins/ibutsu
rm *.tgz
npm pack
cd ../..
mv plugins/ibutsu/*.tgz .
sha256sum *.tgz | awk '{print $1}' | xxd -r -p | base64