---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-app
  title: Test App
  description: |
    Test App is a simple app that does nothing.

  labels:
    service: test-app
    platform: test-platform


  tags:
    - test-app

  annotations:
    ibutsu/component-name: "<----  ADD COMPONENT NAME HERE  ---->"
spec:
  type: application 
  system: test-app
  owner: test-app-app-owners
  lifecycle: OnBoarded
  subcomponentOf: test-app-app
