name: Plugin CI/CD
run-name: Running build pipeline for Ibutsu plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Using Node version ${{ matrix.node-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        name: Install dependencies
      - run: yarn test
        name: Run plugin tests
